defaults: &defaults
  adapter: postgresql
  host: <%= ENV['DATABASE_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DATABASE_PORT_5432_TCP_PORT'] %>
  username: postgres
  password: changeme
  encoding: utf8

development:
  <<: *defaults
  database: "memetrack_development"

test:
  <<: *defaults
  database: "memetrack_test"

production:
  <<: *defaults
  database: "memetrack_production"
