source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'paperclip', '~> 4.2'
gem 'html5-rails'
gem 'turbolinks'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'compass-rails', github: "compass/compass-rails", ref: "4e7d761"

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
